apiVersion: v1
kind: Namespace
metadata:
  name: whoami
  labels:
    name: whoami
    mytag: customvalue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: whoami
  name: whoami
spec:
  strategy:
    type: RollingUpdate
  replicas: 5
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
        version: v2
    spec:
      containers:
      - name: whoami
        image: traefik/whoami:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: whoami
  name: whoami
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: whoami
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 1
---
apiVersion: v1
kind: Service
metadata:
  namespace: whoami # /!\ meme namespace 
  name: whoami
spec:
  selector:
    app: whoami
  type: ClusterIP 
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: whoami
  name: whoami
  labels:
    name: whoami
spec:
  rules:
  - host: whoami.kube
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: whoami
            port: 
              number: 80
