apiVersion: v1
kind: Pod
metadata:
  namespace: intro
  name: nginx
  labels:
    name: nginx
    app: mynginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"  
    ports:
      - containerPort: 80
