apiVersion: v1
kind: Service
metadata:
  namespace: intro # /!\ meme namespace 
  name: nginx
spec:
  selector:
    app: mynginx
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31100
